apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-app.fullname" . }}
  labels:
    app: {{ include "test-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "test-app.name" . }}
    spec:
      containers:
      - name: test-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort.port }}
          name: {{ .Values.containerPort.name }}
          protocol: TCP
