apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}
  labels:
    app: {{ include "test-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "test-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.containerPort.port }}
      name: http
