apiVersion: v1
kind: Service
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.containerPort.port }}
      name: http
